CS 1.0/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS_1._0.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CS_1._0.Controllers
{
    public class CategoryController : Controller
    {
        // GET: /<controller>/
        private readonly ICategoryRepository _categoryRepository;

        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddCategory(Category category)
        {
            _categoryRepository.AddCategory(category);
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult AddingComplete()
        {
            ViewBag.CompleteMessage = "Category was succesfully created!";
            return View("AddingComplete");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveCategory()
        {
            var model = _categoryRepository.AllCategories;
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveCategory(int categoryId)
        {
            _categoryRepository.RemoveCategory(categoryId);
            var model = _categoryRepository.AllCategories;
            return View(model);
        }
    }
}

CS 1.0/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS_1._0.Models;
using CS_1._0.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CS_1._0.Controllers
{
    public class RecordController : Controller
    {
        private readonly IRecordRepository _recordRepository;
        private readonly ICategoryRepository _categoryRepository;

        public RecordController(ICategoryRepository categoryRepository, IRecordRepository recordRepository)
        {
            _recordRepository = recordRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {
            IEnumerable<Record> records;
            string currentCategory;

            if(string.IsNullOrEmpty(category))
            {
                records = _recordRepository.Records.OrderBy(r => r.RecordId);
                currentCategory = "All";
            }
            else
            {
                records = _recordRepository.Records.Where(r => r.Category.CategoryName == category).OrderBy(r => r.RecordId);
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }
            return View(new RecordViewModel { Records = records, CurrentCategory = currentCategory });
        }
        [Authorize(Roles = "Admin")]
        public IActionResult AddRecord()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddRecord(Record record)
        {
            _recordRepository.CreateRecord(record);
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveRecord()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveRecord(int recordId)
        {
            _recordRepository.RemoveRecord(recordId);
            return View("RemoveRecord");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Details(int id)
        {
            var record = _recordRepository.GetRecordByRecordId(id);
            if(record==null)
            {
                return NotFound();
            }
            return View(record);
        }
    }
}

CS 1.0/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CS_1._0.Models;
using CS_1._0.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CS_1._0.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> CreateAsync(string roleName)
        {
            if(!string.IsNullOrEmpty(roleName))
            {
                IdentityResult identityResult = await _roleManager.CreateAsync(new IdentityRole(roleName));
                if(identityResult.Succeeded)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(roleName);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }

            return RedirectToAction("Index"); 
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }


        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                await _signInManager.RefreshSignInAsync(user);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

CS 1.0/Views/Shared/_Headerandtext.cshtml
@model Record
<div style="background-color:black;color:white;padding:20px;">
    <h2>@Model.RecordHeader</h2>
    <p>@Model.RecordDetails</p>

</div>

CS 1.0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Record" asp-action="List">List</a></li>
                        @await Component.InvokeAsync("CategoryMenu")
                        @if (User.IsInRole("Admin"))
                        {
                            <li><a asp-controller="Record" asp-action="AddRecord">Add Record</a></li>
                            <li><a asp-controller="Category" asp-action="AddCategory">Add Category</a></li>
                            <li><a asp-controller="Category" asp-action="RemoveCategory">Remove Category</a></li>
                            <li><a asp-controller="Roles" asp-action="Index">Roles managment</a></li>
                        }
                        <li><partial name="_LoginPartial" /></li>
                    </ul>
                </div>
            </div>
        </nav>


        <div class="row">
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>

    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>

CS 1.0/Views/Shared/_LeftImg.cshtml
@model Record
<div style="background-color:black;color:white;padding:20px;">

    <h2>@Model.RecordHeader</h2>
    <p>
        <img src="@Model.RecordImage" style="float:left;width:42px;height:42px;">
        @Model.RecordDetails
    </p>
</div>

CS 1.0/Views/Shared/_RightImg.cshtml
@model Record
    <div style="background-color:black;color:white;padding:20px;">

        <h2>@Model.RecordHeader</h2>
        <p>
            <img src="@Model.RecordImage" style="float:right;width:42px;height:42px;">
            @Model.RecordDetails
        </p>
    </div>

CS 1.0/Views/Shared/_Slider.cshtml
@model Record
<div style="background-color:black;color:white;padding:20px;">

    <h2>@Model.RecordHeader</h2>
    <p>
        <img src="@Model.RecordImage" style="float:right;width:42px;height:42px;">
        @Model.RecordDetails
    </p>

</div>

CS 1.0/Views/Shared/_Textandimageontheleft.cshtml
@model Record
<div style="background-color:black;color:white;padding:20px;">

    <h2>@Model.RecordHeader</h2>
    <p>
        <img src="@Model.RecordImage" style="float:right;width:42px;height:42px;">
        @Model.RecordDetails
    </p>

</div>

CS 1.0/Views/Shared/_Textandimageontheright.cshtml
@model Record
<div style="background-color:black;color:white;padding:20px;">

    <h2>@Model.RecordHeader</h2>
    <p>
        <img src="@Model.RecordImage" style="float:left;width:42px;height:42px;">
        @Model.RecordDetails
    </p>

</div>

CS 1.0/Views/Shared/_WithoutImg.cshtml
@model Record
<div style="background-color:black;color:white;padding:20px;">
    <h2>@Model.RecordHeader</h2>
    <p>@Model.RecordDetails</p>

</div>